name: AppScan CodeSweep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codesweep:
    name: AppScan CodeSweep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v1.2.0
